# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='photo_link',
            field=models.CharField(default='https://aotw-pd.s3.amazonaws.com/media-vimeo/70533052.jpg', max_length=200),
        ),
    ]
