# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_entity_photo_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='photo_link',
            new_name='photolink',
        ),
    ]
