# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20170910_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='negative_review',
            field=models.IntegerField(default=0, max_length=5000),
        ),
        migrations.AddField(
            model_name='entity',
            name='positive_review',
            field=models.IntegerField(default=0, max_length=5000),
        ),
    ]
