# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20170910_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='negative_review',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='positive_review',
        ),
        migrations.AddField(
            model_name='entity',
            name='officallink',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
    ]
