# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_auto_20170918_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='negative_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='positive_review',
            field=models.IntegerField(default=0),
        ),
    ]
