# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_entity_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(default='cityinfo', max_length=20),
        ),
    ]
