# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
