# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderid', models.IntegerField()),
                ('receiverid', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('time_delivered', models.DateTimeField()),
            ],
        ),
    ]
